on:
  push:
    tags: ["*"]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            goos: darwin
            goarch: arm64
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.goos }}-${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s" -o color
      - run: tar -acf color-${{ matrix.goos }}-${{ matrix.goarch }}.tar.xz color
      - uses: softprops/action-gh-release@v2
        with:
          files: color-${{ matrix.goos }}-${{ matrix.goarch }}.tar.xz
