on:
  push:
    tags: ["*"]

permissions:
  contents: write

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        versions:
          - os: macos-latest
            target: darwin-arm64
          - os: ubuntu-latest
            target: linux-x64
    runs-on: ${{ matrix.versions.os }}
    name: ${{ matrix.versions.target }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build --target bun-${{ matrix.versions.target }} --outfile color-${{ github.ref_name }}-${{ matrix.versions.target }}
      - uses: softprops/action-gh-release@v2
        with:
          files: color-${{ github.ref_name }}-${{ matrix.versions.target }}
